### ISSUE TITLE
Add LocaleKit support

### ISSUE THREAD

**Issue by richienyhus** [HaikuArchives/Paladin#12]

**Comment by adamfowleruk** [comment]
@scottmc I've started to implement this on a branch, but I realise reading PLocale.h that in doing so I'm going to break Zeta build support. Is this a massive problem? (I've never used Zeta, not sure how many people still do). Thanks.

**Comment by pulkomandy** [comment]
No, Zeta is dead. You can drop support for it.

**Comment by adamfowleruk** [comment]
Added PR to solve this issue. English only currently.
