### ISSUE TITLE
Use BButtons in project window

### ISSUE THREAD

**Issue by diversys** [HaikuArchives/Paladin#121]
![image](https://user-images.githubusercontent.com/1316513/46080589-fc816000-c1a2-11e8-9db8-29366e3fa851.png)

**Comment by janus2** [comment]
@diversys do you want to remove the labels? The icons are not very expressive. Try to align a vertical BToolBar with those labels can spiral quickly into madness... Using a Grid layout should be much simpler. Do I miss something?

**Comment by diversys** [comment]
I meant that using BToolbar instead of homegrown icon buttons. I didn't mean to remove the labels.
Or there is another classs with picture buttons?

**Comment by janus2** [comment]
Now BButton supports Images (BBitmap), BToolBar uses BButtons with a layout to accomplish its task.

**Comment by diversys** [comment]
Ah, ok! Adjusted description.

**Comment by adamfowleruk** [comment]
Offending code is StartWindow:84 make_button:-

```cpp

static BitmapButton*
make_button(const char* name, const char* up, const char* down,
	int32 command)
{
	BBitmap* upBitmap = BTranslationUtils::GetBitmap('PNG ', up);
	BBitmap* downBitmap = BTranslationUtils::GetBitmap('PNG ', down);
	BitmapButton* button = new BitmapButton(name, upBitmap, downBitmap,
		new BMessage(command));
	button->SetExplicitSize(BSize(31, 31));

	return button;
}
```
