### ISSUE TITLE
Draw border around statusbar

### ISSUE THREAD

**Issue by diversys** [HaikuArchives/Paladin#143]
![image](https://user-images.githubusercontent.com/1316513/46205825-ca026f00-c32a-11e8-92df-f7883b597177.png)

**Comment by adamfowleruk** [comment]
Yep agreed. Will also sort out the 1 pixel shifting of the scroll bar upwards.

**Comment by diversys** [comment]
Applied this patch and 1 pixel shifting is still there. Before it was 2 pixels tho.

**Comment by adamfowleruk** [comment]
Odd. Can you add a screenshot please? It appears with no pixel shifting on my build. Thanks.

**Comment by diversys** [comment]
![image](https://user-images.githubusercontent.com/1316513/46212988-0b514980-c340-11e8-9099-08836979ae0e.png)

**Comment by diversys** [comment]
Compared to StyledEdit at the top.

**Comment by adamfowleruk** [comment]
Ah you mean the scollbar not the status bar? Top and bottom are one pixel larger than in StyledEdit, yes?

**Comment by diversys** [comment]
Scollbar yes, sorry. One pixel larger indeed.

**Comment by adamfowleruk** [comment]
Should be fixed now. Please retest the commit in the PR.

**Comment by diversys** [comment]
Could you please fix the same bug in WebPositive (2 pixel shifting of the scroll bar upwards)?
