### ISSUE TITLE
dev-utils fastdep and ccache

### ISSUE THREAD

**Issue by scottmc** [HaikuArchives/Paladin#154]
The original paladin made use of fastdep and ccache and included those in the downloadable zip file.  We have since created recipes to build packages for both of them, the recipes can be found in:
https://github.com/haikuports/haikuports/tree/master/dev-util
Not sure if the code still tries to make use of these or not. figured I'd point them out.  There may also be other useful libraries and utils that we have recipes for or can make recipes for.  If you find any that need to be create, just open a new issue on haikuports and we will add it as a possible target.

**Comment by adamfowleruk** [comment]
I have seen in the code checks for these. If they exist on the system they are used. I've not tested them myself though, so I'll mark this as investigate for the current milestone.

**Comment by adamfowleruk** [comment]
See #208 ccache and #209 fastdep
