### ISSUE TITLE
Test x86 32-bit build prior to 2.0 release

### ISSUE THREAD

**Issue by adamfowleruk** [HaikuArchives/Paladin#168]

**Comment by scottmc** [comment]
If you could check the new version vs. the screenshots and such in Jon's book, that'd be cool.  We use his book along with Paladin during Google Code-In.  Here's the task https://dev.haiku-os.org/wiki/GoogleCodeInTaskBook1
The book is linked in there. Hopefully the code hasn't diverged too much and students will still find it works as expected.  Here's the book 2 task, which likely had more references to Paladin. https://dev.haiku-os.org/wiki/GoogleCodeInTaskBook2

**Comment by adamfowleruk** [comment]
Oh wow didn't realise that existed. I'll definitely check it out when working on this.

**Comment by adamfowleruk** [comment]
Build for 2.0 tested on x86 as working by @humdingerb . Moving the book for the developer flow version (to match with the work on templates for students)
