### ISSUE TITLE
Incorrect paths to header files in generated makefile

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/Paladin#18]
When Paladin is used to generate a project makefile, the paths to system headers is incorrect
Eg. /boot/develop/headers/posix should be /boot/system/develop/headers/posix

**Comment by BachToTheFuture** [comment]
I think I could handle this :)

**Comment by Vidrep** [comment]
This issue goes hand in hand with https://github.com/HaikuArchives/Paladin/issues/16

**Comment by Vidrep** [comment]
Depending on whether you're using gcc2 or gcc5, the header files are in different paths.
/boot/system/develop/headers/cpp should be /boot/system/develop/headers/c++/2.95.3 for gcc2

**Comment by bach5000** [comment]
@Vidrep so I would use `#ifdef HAIKU_GCC` or something like that, right?
