### ISSUE TITLE
Incorporate samples from Haiku Examples code

### ISSUE THREAD

**Issue by adamfowleruk** [HaikuArchives/Paladin#194]
Create sample and template based on these samples:-
https://github.com/drcouzelis/HaikuApiExamples

**Comment by adamfowleruk** [comment]
Working on this now

**Comment by pulkomandy** [comment]
Your commit mentions the Be Book, which is worrying because we are not allowed to use it this way (it is under a creative commons no-derivatives license). That's the reason we have the haiku book, and drcouzelis work on a new set of samples.

**Comment by adamfowleruk** [comment]
No it was me not having enough sleep. They were from the URL you provided, which in turn is code from DarkWyrm's haiku tutorial, not the Be Book.
