### ISSUE TITLE
UX: Paladin doesn't respect system colors

### ISSUE THREAD

**Issue by cb88** [HaikuArchives/Paladin#227]
List text appears to be hard coded, it should respect system colors and or use slight variations of the system colors (like to denote an inactive but recently changed file would be the same as the inactive color with an offset intensity either brighter/darker).

Also not sure what is going on with Driver.cpp... that doesn't look ideal either.

![paladin_black](https://user-images.githubusercontent.com/1026000/47967435-4d4e6900-e02b-11e8-985c-2cdcb9672afd.png)
![paladin_grey](https://user-images.githubusercontent.com/1026000/47967436-4d4e6900-e02b-11e8-8e6a-5ab690e11cc5.png)

**Comment by adamfowleruk** [comment]
Good catch

**Comment by adamfowleruk** [comment]
Source group headings do not respect system colours still. From nephele.
