### ISSUE TITLE
Paladin Crashes when trying to create a new Project

### ISSUE THREAD

**Issue by atariVCS** [HaikuArchives/Paladin#239]
Installed Paladin 2 and Paladin "1" from HAIKU Depot.
In the Debugger it shows a Segment Violation.
I'm currently using HAIKU Beta1 with updates (hrev52295+104, x86, Kernel Nov. 4th, 9:38:50 AM).

file:///boot/home/Desktop/Paladin-8745-debug-14-11-2018-05-51-03.report

**Comment by atariVCS** [comment]
Tring to upload the HAIKU Debugger Repor...

**Comment by atariVCS** [comment]
Debug information for team /boot/system/apps/Paladin/Paladin (8745):
CPU(s): 2x Intel Core™ i7-3820
Memory: 1.56 GiB total, 772.95 MiB used
Haiku revision: hrev52295+104 Nov  4 2018 09:38 (BePC)

Active Threads:
	thread 8745: Paladin (main)
	thread 8764: w>Paladin: Projekt öffnen 
	thread 8767: w>Paladin: Projektordner wähle 
	thread 8785: team 8745 debug task 
	thread 8769: w>Paladin: Start 
		state: Exception (Segment violation)

		Frame		IP			Function Name
		-----------------------------------------------
		0x7151b7f0	0x14d3249	__14TemplateWindowRC5BRect + 0x2d1 
			Disassembly:
				__14TemplateWindowRC5BRect:
				0x014d2f78:               55  push %ebp
				0x014d2f79:             89e5  mov %esp, %ebp
				0x014d2f7b:     81ecfc000000  sub $0xfc, %esp
				0x014d2f81:               57  push %edi
				0x014d2f82:               56  push %esi
				0x014d2f83:               53  push %ebx
				0x014d2f84:       e800000000  call 0x14d2f89
				0x014d2f89:               5b  pop %ebx
				0x014d2f8a:     81c313a90500  add $0x5a913, %ebx
				0x014d2f90:           8b450c  mov 0xc(%ebp), %eax
				0x014d2f93:             d900  fld (%eax)
				0x014d2f95:           d95df0  fstp -0x10(%ebp)
				0x014d2f98:           d94004  fld 0x4(%eax)
				0x014d2f9b:           d95df4  fstp -0xc(%ebp)
				0x014d2f9e:           d94008  fld 0x8(%eax)
				0x014d2fa1:           d95df8  fstp -0x8(%ebp)
				0x014d2fa4:           d9400c  fld 0xc(%eax)
				0x014d2fa7:           d95dfc  fstp -0x4(%ebp)
				0x014d2faa:           83c4f8  add $0xfffffff8, %esp
				0x014d2fad:             6a00  push $0x0
				0x014d2faf:       6842004000  push $0x400042
				0x014d2fb4:             6a01  push $0x1
				0x014d2fb6:             6a00  push $0x0
				0x014d2fb8:     8dbbb0f0fdff  lea -0x20f50(%ebx), %edi
				0x014d2fbe:               57  push %edi
				0x014d2fbf:     8d83bff0fdff  lea -0x20f41(%ebx), %eax
				0x014d2fc5:               50  push %eax
				0x014d2fc6:           83c4f4  add $0xfffffff4, %esp
				0x014d2fc9:       e84e14fbff  call 0x148441c
				0x014d2fce:               50  push %eax
				0x014d2fcf:       e87c000300  call 0x1503050
				0x014d2fd4:           83c410  add $0x10, %esp
				0x014d2fd7:               50  push %eax
				0x014d2fd8:       e81f0efbff  call 0x1483dfc
				0x014d2fdd:           83c410  add $0x10, %esp
				0x014d2fe0:               50  push %eax
				0x014d2fe1:           8d45f0  lea -0x10(%ebp), %eax
				0x014d2fe4:               50  push %eax
				0x014d2fe5:           8b4508  mov 0x8(%ebp), %eax
				0x014d2fe8:               50  push %eax
				0x014d2fe9:       e8de0cfbff  call 0x1483ccc
				0x014d2fee:     8b83080d0000  mov 0xd08(%ebx), %eax
				0x014d2ff4:           8b5508  mov 0x8(%ebp), %edx
				0x014d2ff7:           894208  mov %eax, 0x8(%edx)
				0x014d2ffa:           83c420  add $0x20, %esp
				0x014d2ffd:           83c4f4  add $0xfffffff4, %esp
				0x014d3000:     81c290010000  add $0x190, %edx
				0x014d3006:           895580  mov %edx, -0x80(%ebp)
				0x014d3009:               52  push %edx
				0x014d300a:       e8b9e8ffff  call 0x14d18c8
				0x014d300f:           83c410  add $0x10, %esp
				0x014d3012:       e8b130fdff  call 0x14a60c8
				0x014d3017:           83c4f4  add $0xfffffff4, %esp
				0x014d301a:           8b4d08  mov 0x8(%ebp), %ecx
				0x014d301d:               51  push %ecx
				0x014d301e:       e849230000  call 0x14d536c
				0x014d3023:           83c4f8  add $0xfffffff8, %esp
				0x014d3026:           83c4f4  add $0xfffffff4, %esp
				0x014d3029:     8b831c0a0000  mov 0xa1c(%ebx), %eax
				0x014d302f:               50  push %eax
				0x014d3030:       e8fbc20100  call 0x14ef330
				0x014d3035:               50  push %eax
				0x014d3036:           8d75d8  lea -0x28(%ebp), %esi
				0x014d3039:               56  push %esi
				0x014d303a:       e835b60100  call 0x14ee674
				0x014d303f:           83c430  add $0x30, %esp
				0x014d3042:           83c4f8  add $0xfffffff8, %esp
				0x014d3045:             6a00  push $0x0
				0x014d3047:               57  push %edi
				0x014d3048:     8d83d5f0fdff  lea -0x20f2b(%ebx), %eax
				0x014d304e:               50  push %eax
				0x014d304f:           83c4f4  add $0xfffffff4, %esp
				0x014d3052:       e8c513fbff  call 0x148441c
				0x014d3057:               50  push %eax
				0x014d3058:       e8f3ff0200  call 0x1503050
				0x014d305d:           83c410  add $0x10, %esp
				0x014d3060:               50  push %eax
				0x014d3061:       e8960dfbff  call 0x1483dfc
				0x014d3066:               50  push %eax
				0x014d3067:               56  push %esi
				0x014d3068:       e8ebc40100  call 0x14ef558
				0x014d306d:           83c420  add $0x20, %esp
				0x014d3070:           83c4f8  add $0xfffffff8, %esp
				0x014d3073:           83c4f4  add $0xfffffff4, %esp
				0x014d3076:               56  push %esi
				0x014d3077:       e870c20100  call 0x14ef2ec
				0x014d307c:               50  push %eax
				0x014d307d:           8b4580  mov -0x80(%ebp), %eax
				0x014d3080:               50  push %eax
				0x014d3081:       e876e8ffff  call 0x14d18fc
				0x014d3086:           83c420  add $0x20, %esp
				0x014d3089:           83c4f4  add $0xfffffff4, %esp
				0x014d308c:       6854010000  push $0x154
				0x014d3091:       e84618fbff  call 0x14848dc
				0x014d3096:             89c6  mov %eax, %esi
				0x014d3098:   c6857bffffff01  mov $0x1, -0x85(%ebp)
				0x014d309f:           83c4f4  add $0xfffffff4, %esp
				0x014d30a2:             6a01  push $0x1
				0x014d30a4:           83c4fe  add $0xfffffffe, %esp
				0x014d30a7:           666a01  push $0x1
				0x014d30aa:           83c4fe  add $0xfffffffe, %esp
				0x014d30ad:           666a01  push $0x1
				0x014d30b0:             6a00  push $0x0
				0x014d30b2:               57  push %edi
				0x014d30b3:     8d83dff0fdff  lea -0x20f21(%ebx), %eax
				0x014d30b9:               50  push %eax
				0x014d30ba:           83c4f4  add $0xfffffff4, %esp
				0x014d30bd:       e85a13fbff  call 0x148441c
				0x014d30c2:               50  push %eax
				0x014d30c3:       e888ff0200  call 0x1503050
				0x014d30c8:           83c410  add $0x10, %esp
				0x014d30cb:               50  push %eax
				0x014d30cc:       e82b0dfbff  call 0x1483dfc
				0x014d30d1:           83c410  add $0x10, %esp
				0x014d30d4:               50  push %eax
				0x014d30d5:               56  push %esi
				0x014d30d6:       e8a113fbff  call 0x148447c
				0x014d30db:   c6857bffffff00  mov $0x0, -0x85(%ebp)
				0x014d30e2:     89857cffffff  mov %eax, -0x84(%ebp)
				0x014d30e8:           83c430  add $0x30, %esp
				0x014d30eb:             eb0b  jmp 0x14d30f8
				0x014d30ed:           8d7600  lea (%esi), %esi
				0x014d30f0:       e83704fbff  call 0x148352c
				0x014d30f5:           8d7600  lea (%esi), %esi
				0x014d30f8:   80bd7bffffff00  cmp $0x0, -0x85(%ebp)
				0x014d30ff:             740c  jz 0x14d310d
				0x014d3101:           83c4f4  add $0xfffffff4, %esp
				0x014d3104:               56  push %esi
				0x014d3105:       e89217fbff  call 0x148489c
				0x014d310a:           83c410  add $0x10, %esp
				0x014d310d: c78574ffffff0000  mov $0x0, -0x8c(%ebp)
				0x014d3117:       e9f7000000  jmp 0x14d3213
				0x014d311c:           83c4f8  add $0xfffffff8, %esp
				0x014d311f:     8b9574ffffff  mov -0x8c(%ebp), %edx
				0x014d3125:               52  push %edx
				0x014d3126:           8b4508  mov 0x8(%ebp), %eax
				0x014d3129:       0590010000  add $0x190, %eax
				0x014d312e:               50  push %eax
				0x014d312f:       e80ceaffff  call 0x14d1b40
				0x014d3134:             89c2  mov %eax, %edx
				0x014d3136:           8d45f0  lea -0x10(%ebp), %eax
				0x014d3139:           83c4f8  add $0xfffffff8, %esp
				0x014d313c:               52  push %edx
				0x014d313d:               50  push %eax
				0x014d313e:       e895eeffff  call 0x14d1fd8
				0x014d3143:       6880000000  push $0x80
				0x014d3148:       e88f17fbff  call 0x14848dc
				0x014d314d:             89c7  mov %eax, %edi
				0x014d314f:   c68573ffffff01  mov $0x1, -0x8d(%ebp)
				0x014d3156:           83c420  add $0x20, %esp
				0x014d3159:           83c4f4  add $0xfffffff4, %esp
				0x014d315c:             6a48  push $0x48
				0x014d315e:       e8a918fbff  call 0x1484a0c
				0x014d3163:             89c6  mov %eax, %esi
				0x014d3165:   c68572ffffff01  mov $0x1, -0x8e(%ebp)
				0x014d316c:           83c4f8  add $0xfffffff8, %esp
				0x014d316f:       686c736d74  push $0x746d736c
				0x014d3174:               56  push %esi
				0x014d3175:       e86200fbff  call 0x14831dc
				0x014d317a:   c68572ffffff00  mov $0x0, -0x8e(%ebp)
				0x014d3181:           83c4f4  add $0xfffffff4, %esp
				0x014d3184:             6a00  push $0x0
				0x014d3186:             6a00  push $0x0
				0x014d3188:               50  push %eax
				0x014d3189:           8b45fc  mov -0x4(%ebp), %eax
				0x014d318c:               50  push %eax
				0x014d318d:               57  push %edi
				0x014d318e:       e899f7faff  call 0x148292c
				0x014d3193:   c68573ffffff00  mov $0x0, -0x8d(%ebp)
				0x014d319a:           83c4f4  add $0xfffffff4, %esp
				0x014d319d:               50  push %eax
				0x014d319e:     8b8d7cffffff  mov -0x84(%ebp), %ecx
				0x014d31a4:               51  push %ecx
				0x014d31a5:       e8f200fbff  call 0x148329c
				0x014d31aa:           83c454  add $0x54, %esp
				0x014d31ad:             eb09  jmp 0x14d31b8
				0x014d31af:               90  nop 
				0x014d31b0:       e87703fbff  call 0x148352c
				0x014d31b5:           8d7600  lea (%esi), %esi
				0x014d31b8:   80bd72ffffff00  cmp $0x0, -0x8e(%ebp)
				0x014d31bf:             741b  jz 0x14d31dc
				0x014d31c1:           83c4f8  add $0xfffffff8, %esp
				0x014d31c4:             6a48  push $0x48
				0x014d31c6:               56  push %esi
				0x014d31c7:       e86015fbff  call 0x148472c
				0x014d31cc:           83c410  add $0x10, %esp
				0x014d31cf:             eb0b  jmp 0x14d31dc
				0x014d31d1:           8d7600  lea (%esi), %esi
				0x014d31d4:       e85303fbff  call 0x148352c
				0x014d31d9:           8d7600  lea (%esi), %esi
				0x014d31dc:   80bd73ffffff00  cmp $0x0, -0x8d(%ebp)
				0x014d31e3:             7417  jz 0x14d31fc
				0x014d31e5:           83c4f4  add $0xfffffff4, %esp
				0x014d31e8:               57  push %edi
				0x014d31e9:       e8ae16fbff  call 0x148489c
				0x014d31ee:           83c410  add $0x10, %esp
				0x014d31f1:             eb09  jmp 0x14d31fc
				0x014d31f3:               90  nop 
				0x014d31f4:       e83303fbff  call 0x148352c
				0x014d31f9:           8d7600  lea (%esi), %esi
				0x014d31fc:           83c4f8  add $0xfffffff8, %esp
				0x014d31ff:             6a02  push $0x2
				0x014d3201:           8d45f0  lea -0x10(%ebp), %eax
				0x014d3204:               50  push %eax
				0x014d3205:       e8b20cfbff  call 0x1483ebc
				0x014d320a:           83c410  add $0x10, %esp
				0x014d320d:     ff8574ffffff  inc -0x8c(%ebp)
				0x014d3213:           83c4f4  add $0xfffffff4, %esp
				0x014d3216:           8b4508  mov 0x8(%ebp), %eax
				0x014d3219:       0590010000  add $0x190, %eax
				0x014d321e:               50  push %eax
				0x014d321f:       e858ebffff  call 0x14d1d7c
				0x014d3224:           83c410  add $0x10, %esp
				0x014d3227:     398574ffffff  cmp %eax, -0x8c(%ebp)
				0x014d322d:     0f8ce9feffff  jl 0x14d311c
				0x014d3233:           83c4f8  add $0xfffffff8, %esp
				0x014d3236:           83c4f8  add $0xfffffff8, %esp
				0x014d3239:             6a00  push $0x0
				0x014d323b:     8b857cffffff  mov -0x84(%ebp), %eax
				0x014d3241:               50  push %eax
				0x014d3242:       e82515fbff  call 0x148476c
				0x014d3247:             89c1  mov %eax, %ecx
				0x014d3249:           8b4108  mov 0x8(%ecx), %eax <--

			Frame memory:
				[0x7151b6c8]  H4~.......|.....   48 34 7e 18 00 00 00 00 80 f4 7c 18 00 00 00 00
				[0x7151b6d8]  ..Qq.0M...R...|.   e8 b7 51 71 17 30 4d 01 9c d8 52 01 f0 f2 7c 18
				[0x7151b6e8]  ..|..%..0.....|.   c8 b7 7c 18 f1 25 f8 00 30 e8 02 01 e8 f2 7c 18
				[0x7151b6f8]  ..|.."......d...   c8 b7 7c 18 c1 22 00 01 ec f5 b1 01 64 00 00 00
				[0x7151b708]  8.Qq....$.z...Qq   38 b7 51 71 f7 d2 ff 00 24 ff 7a 18 f0 b7 51 71
				[0x7151b718]  h.Qq....0.....|.   68 b7 51 71 e4 d2 ff 00 30 e8 02 01 e8 f2 7c 18
				[0x7151b728]  .....[....Qq....   02 00 00 00 b3 5b 8f 01 c8 b7 51 71 10 00 00 00
				[0x7151b738]  ..Qq}...$.z...Qq   88 b7 51 71 7d 1a 00 01 24 ff 7a 18 c8 b7 51 71
				[0x7151b748]  .{{.Z...0.......   98 7b 7b 18 5a 0e 00 01 30 e8 02 01 b4 01 00 00
				[0x7151b758]  ..|......Y..H4~.   c8 b7 7c 18 00 00 00 00 9c 59 f8 00 48 34 7e 18
				[0x7151b768]  ..|..Z........|.   80 f4 7c 18 db 5a 8f 01 00 00 00 00 f0 dc 7c 18
				[0x7151b778]  ..z...Qq......|.   00 d0 7a 18 84 b7 51 71 12 00 00 00 e8 f2 7c 18
				[0x7151b788]  ..Qq( ....z.....   b8 b7 51 71 28 20 00 01 8c fb 7a 18 b4 01 00 00
				[0x7151b798]  ..Qq....0.......   f8 b7 51 71 b1 1e 00 01 30 e8 02 01 b4 01 00 00
				[0x7151b7a8]  ............,...   00 00 00 00 00 00 00 00 ec f5 b1 01 2c 14 7f 18
				[0x7151b7b8]  ..Qq.t..h.{.p)..   e8 b7 51 71 ed 74 f7 00 68 fe 7b 18 70 29 84 18
				[0x7151b7c8]  P............7S.   50 13 84 18 1a 00 00 00 00 00 00 00 98 37 53 01
				[0x7151b7d8]  ...........C..HC   00 00 00 00 00 00 00 00 00 00 96 43 00 00 48 43
				[0x7151b7e8]  8.Qq..M.           38 b8 51 71 f1 12 4d 01
		0x7151b840	0x14d12ec	StartWindow::MessageReceived(BMessage*) + 0xd8 
		0x7151b870	0x18e6bdd	BLooper::DispatchMessage(BMessage*, BHandler*) + 0x59 
		0x7151ba50	0x19d0ae0	BWindow::DispatchMessage(BMessage*, BHandler*) + 0x182c 
		0x7151bab0	0x19d51f2	BWindow::task_looper() + 0x28e 
		0x7151bae0	0x18e8085	BLooper::_task0_(void*) + 0x3d 
		0x7151bb08	0xf80b1d	thread_entry + 0x21 
		00000000	0x61380250	commpage_thread_exit + 0 

		Registers:
			  eip:	0x014d3249
			  esp:	0x7151b6c8
			  ebp:	0x7151b7e8
			  eax:	0x00000000
			  ebx:	0x0152d89c
			  ecx:	0x00000000
			  edx:	0x00000000
			  esi:	0x187e3448
			  edi:	0x0150c94c
			   cs:	0x001b
			   ds:	0x0023
			   es:	0x0023
			   fs:	0x0063
			   gs:	0x0023
			   ss:	0x0023
			  st0:	0
			  st1:	0
			  st2:	0.9
			  st3:	14
			  st4:	1
			  st5:	2
			  st6:	1
			  st7:	1
			  mm0:	{0, 0, 0, 0}
			  mm1:	{0, 0, 0, 0}
			  mm2:	{0, 0, 0x6600, 0xe666}
			  mm3:	{0, 0, 0, 0xe000}
			  mm4:	{0, 0, 0, 0x8000}
			  mm5:	{0, 0, 0, 0x8000}
			  mm6:	{0, 0, 0, 0x8000}
			  mm7:	{0, 0, 0, 0x8000}
			 xmm0:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm1:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm2:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm3:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm4:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm5:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm6:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm7:	{0, 0, 0, 0, 0, 0, 0, 0}

Loaded Images:
	ID		Text Base	Text End	Data Base	Data End	Type	Name
	--------------------------------------------------------------------------------
	3168	0x0089c000	0x008a5000	0x008a5000	0x008a7000	lib    	/boot/system/lib/libicuio.so.57.1
	3167	0x00916000	0x00ba7000	0x00ba7000	0x00c10000	lib    	/boot/system/lib/libicui18n.so.57.1
	3158	0x00d51000	0x00d70000	0x00d70000	0x00d73000	lib    	/boot/system/runtime_loader
	3171	0x00e87000	0x00ec0000	0x00ec0000	0x00ef7000	lib    	/boot/system/lib/libicutu.so.57.1
	3165	0x00f4e000	0x01024000	0x01024000	0x01070000	lib    	/boot/system/lib/libroot.so
	3170	0x011a4000	0x011af000	0x011af000	0x011b2000	lib    	/boot/system/lib/libiculx.so.57.1
	3163	0x013db000	0x013f2000	0x013f2000	0x013f7000	lib    	/boot/system/lib/libtranslation.so
	3159	0x01441000	0x01510000	0x01510000	0x01537000	app    	/boot/system/apps/Paladin/Paladin
	3164	0x016c8000	0x016f9000	0x016f9000	0x01707000	lib    	/boot/system/lib/libstdc++.r4.so
	3169	0x01749000	0x0179c000	0x0179c000	0x017a7000	lib    	/boot/system/lib/libicule.so.57.1
	3160	0x017d3000	0x01aa5000	0x01aa5000	0x01b3e000	lib    	/boot/system/lib/libbe.so
	3173	0x01b99000	0x01bb3000	0x01bb3000	0x01bb4000	lib    	/boot/system/lib/libz.so.1.2.11
	3161	0x01c5c000	0x01e0c000	0x01e0c000	0x01e6c000	lib    	/boot/system/lib/libtracker.so
	3172	0x01f0c000	0x0207e000	0x0207e000	0x020b2000	lib    	/boot/system/lib/libicuuc.so.57.1
	3174	0x02467000	0x0255e000	0x0255e000	0x02561000	lib    	/boot/system/lib/libtextencoding.so
	3162	0x0263d000	0x0267d000	0x0267d000	0x0267f000	lib    	/boot/system/lib/libpcre.so.1.2.10
	3166	0x02c9d000	0x0451b000	0x0451b000	0x0451c000	lib    	/boot/system/lib/libicudata.so.57.1
	3157	0x61380000	0x61388000	0x00000000	0x00000000	system 	commpage

Areas:
	ID		Base		End			Size (KiB)	Protection	Locking			Name
	--------------------------------------------------------------------------------
	27276	0x0010e000	0x0011e000	        64	rw-        	full          	rld heap
	27275	0x00162000	0x00172000	        64	rw-        	full          	rld heap
	27274	0x001bd000	0x001c5000	        32	rw-        	full          	rld heap
	27232	0x00255000	0x00256000	         4	rw-S       	full          	_rld_debug_
	27231	0x0025d000	0x0026d000	        64	rw-        	full          	rld heap
	27257	0x0089c000	0x008a5000	        36	r-x        	full          	libicuio.so.57.1_seg0ro
	27258	0x008a5000	0x008a7000	         8	rw-        	full          	libicuio.so.57.1_seg1rw
	27254	0x00916000	0x00ba7000	      2628	r-x        	full          	libicui18n.so.57.1_seg0ro
	27255	0x00ba7000	0x00c0f000	       416	rw-        	full          	libicui18n.so.57.1_seg1rw
	27256	0x00c0f000	0x00c10000	         4	rw-        	full          	libicui18n.so.57.1_seg2rw
	27228	0x00d51000	0x00d70000	       124	r-x        	full          	runtime_loader_seg0ro
	27229	0x00d70000	0x00d72000	         8	rw-        	full          	runtime_loader_seg1rw
	27230	0x00d72000	0x00d73000	         4	rw-        	full          	runtime_loader_bss1
	27263	0x00e87000	0x00ec0000	       228	r-x        	full          	libicutu.so.57.1_seg0ro
	27264	0x00ec0000	0x00ec5000	        20	rw-        	full          	libicutu.so.57.1_seg1rw
	27265	0x00ec5000	0x00ef7000	       200	rw-        	full          	libicutu.so.57.1_seg2rw
	27249	0x00f4e000	0x01024000	       856	r-x        	full          	libroot.so_seg0ro
	27250	0x01024000	0x01038000	        80	rw-        	full          	libroot.so_seg1rw
	27251	0x01038000	0x01070000	       224	rw-        	full          	libroot.so_seg2rw
	27261	0x011a4000	0x011af000	        44	r-x        	full          	libiculx.so.57.1_seg0ro
	27262	0x011af000	0x011b2000	        12	rw-        	full          	libiculx.so.57.1_seg1rw
	27244	0x013db000	0x013f2000	        92	r-x        	full          	libtranslation.so_seg0ro
	27245	0x013f2000	0x013f7000	        20	rw-        	full          	libtranslation.so_seg1rw
	27233	0x01441000	0x01510000	       828	r-x        	full          	Paladin_seg0ro
	27234	0x01510000	0x01536000	       152	rw-        	full          	Paladin_seg1rw
	27235	0x01536000	0x01537000	         4	rw-        	full          	Paladin_seg2rw
	27246	0x016c8000	0x016f9000	       196	r-x        	full          	libstdc++.r4.so_seg0ro
	27247	0x016f9000	0x01704000	        44	rw-        	full          	libstdc++.r4.so_seg1rw
	27248	0x01704000	0x01707000	        12	rw-        	full          	libstdc++.r4.so_seg2rw
	27259	0x01749000	0x0179c000	       332	r-x        	full          	libicule.so.57.1_seg0ro
	27260	0x0179c000	0x017a7000	        44	rw-        	full          	libicule.so.57.1_seg1rw
	27236	0x017d3000	0x01aa5000	      2888	r-x        	full          	libbe.so_seg0ro
	27237	0x01aa5000	0x01b3d000	       608	rw-        	full          	libbe.so_seg1rw
	27238	0x01b3d000	0x01b3e000	         4	rw-        	full          	libbe.so_seg2rw
	27269	0x01b99000	0x01bb3000	       104	r-x        	full          	libz.so.1.2.11_seg0ro
	27270	0x01bb3000	0x01bb4000	         4	rw-        	full          	libz.so.1.2.11_seg1rw
	27239	0x01c5c000	0x01e0c000	      1728	r-x        	full          	libtracker.so_seg0ro
	27240	0x01e0c000	0x01e6a000	       376	rw-        	full          	libtracker.so_seg1rw
	27241	0x01e6a000	0x01e6c000	         8	rw-        	full          	libtracker.so_seg2rw
	27266	0x01f0c000	0x0207e000	      1480	r-x        	full          	libicuuc.so.57.1_seg0ro
	27267	0x0207e000	0x020b1000	       204	rw-        	full          	libicuuc.so.57.1_seg1rw
	27268	0x020b1000	0x020b2000	         4	rw-        	full          	libicuuc.so.57.1_seg2rw
	27271	0x02467000	0x0255e000	       988	r-x        	full          	libtextencoding.so_seg0ro
	27272	0x0255e000	0x02560000	         8	rw-        	full          	libtextencoding.so_seg1rw
	27273	0x02560000	0x02561000	         4	rw-        	full          	libtextencoding.so_seg2rw
	27242	0x0263d000	0x0267d000	       256	r-x        	full          	libpcre.so.1.2.10_seg0ro
	27243	0x0267d000	0x0267f000	         8	rw-        	full          	libpcre.so.1.2.10_seg1rw
	27252	0x02c9d000	0x0451b000	     25080	r-x        	full          	libicudata.so.57.1_seg0ro
	27253	0x0451b000	0x0451c000	         4	rw-        	full          	libicudata.so.57.1_seg1rw
	27277	0x187ad000	0x1895d000	      1728	rw-        	full          	heap
	27224	0x60ecc000	0x60ed0000	        16	rw-        	full          	user area
	27227	0x61380000	0x61388000	        32	r-xSk      	full          	commpage
	27284	0x61388000	0x61389000	         4	rw-S       	full          	server_memory
	27286	0x69388000	0x693a8000	       128	rw-S       	full          	server_memory
	28109	0x714d8000	0x7151d000	       276	rw-s       	full          	w>Paladin: Start_8769_stack
	28099	0x716b7000	0x716fc000	       276	rw-s       	full          	w>TrackerWindow_8764_stack
	27226	0x7193d000	0x7293e000	     16388	rw-s       	full          	Paladin_8745_stack
	28105	0x72bc7000	0x72c0c000	       276	rw-s       	full          	w>TrackerWindow_8767_stack

Protection Flags: r - read, w - write, x - execute, s - stack, o - overcommit, c - cloneable, S - shared, k - kernel

Semaphores:
	ID		Count	Last Holder	Name
	------------------------------------------------------------
	189741	    0	          0	some BBlockCache lock
	189745	    0	          0	Catalog
	189746	    0	          0	some BLocker
	189756	    0	          0	Light Lock
	189757	    0	       1431	undo
	189758	    0	       1431	some BLocker
	189759	    0	          0	LocaleRosterData
	189760	    0	       1431	token space
	189761	    0	       8776	BLooperList lock
	189762	    0	       8781	AppServerLink_sLock
	189763	    0	       1431	some BLocker
	189764	    0	       1431	Light Lock
	189765	    0	       5712	Catalog
	189766	    0	          0	PeriodicUpdatePoses
	189769	    0	          0	BMessageQueue Lock
	189770	    0	          0	Catalog
	189771	    0	          0	some BLocker
	189772	    0	       1431	Settings
	189773	    0	       1431	some BLocker
	189774	    0	          0	some BLocker
	189776	    0	       5713	AppLooperPort
	189777	    0	       1431	clipboard
	189785	    0	       1482	width buffer
	189788	    0	       1431	screen list
	189824	    0	          0	some BLocker
	189825	    0	          0	Paladin: Start
	189832	    0	          0	BMessageQueue Lock
	189839	    0	       8764	TrackerWindow
	189840	    0	          0	BMessageQueue Lock
	189842	    0	          0	tool tip manager
	189848	    0	       1431	some BLocker
	189850	    0	          0	some BLocker
	189851	    0	          0	Tracker shared icon cache
	189855	    0	          0	Tracker node icon cache
	189857	    0	       5720	virtual directory manager
	189858	    0	          0	Catalog
	189863	    0	          0	BMessageQueue Lock
	189864	    0	       8767	TrackerWindow
	189876	    0	       1431	some BLocker
	190654	    0	          0	Projekttap wählen
	190658	    0	          0	BMessageQueue Lock

**Comment by atariVCS** [comment]
What I found out:
I now did a retest with freshly installed english HAIKU 64 bit (hrev52295+96, x86_64, Kernel of September 27th) and there it works.
I also rechecked with the same system updated with "SoftwareUpdater" to hrev5...+, Kernel of November 4th, and there it also works.
So could be a language or a 32bit Issue.

**Comment by adamfowleruk** [comment]
Did you check an updated Haiku image in German, or only in English?

**Comment by atariVCS** [comment]
Hi. I tested on both the German and the English OS. However I think the issue has already been answered on the HAIKU Forum and somebody already created a PR - so I guess it was definitfely the German language.

**Comment by adamfowleruk** [comment]
Yes, now fixed in PR. Please test and re-open if not.
