### ISSUE TITLE
Driver code

### ISSUE THREAD

**Issue by earl-colby-pottinger** [HaikuArchives/Paladin#241]
If I tried to make a driver, then tell it to generate a makefile, the makefile created is incorrect to making a driver.

I don`t know if I am doing it wrong, but it appears I can`t compile my driver code in Paladin either.

**Comment by adamfowleruk** [comment]
Hello,

Yes I believe this template was never completed. This is highlighted in a feature enhancement bug scheduled for milestone 03 of Paladin.

**Comment by earl-colby-pottinger** [comment]
Thank you for the answer.
