### ISSUE TITLE
ld: cannot find -lsupc++

### ISSUE THREAD

**Issue by dewf** [HaikuArchives/Paladin#242]
When attempting to create and build a new "GUI with main window" project:

    /packages/gcc-2.95.3_2017_07_20-2/.self/develop/tools/i586-pc-haiku/bin/ld: cannot find -lsupc++
    collect2: ld returned 1 exit status

- Haiku version R1/beta1 (also tried with hrev52957 nightly)
- using both HaikuDepot version (version 2.0 d0) and latest git version (Nov 14, 2018 commit)

location of actual files (typed by hand, hopefully no typos):
- /boot/system/develop/tools/x86/lib/gcc/i586-pc-haiku/7.3.0/libsupc++.a
- /boot/system/develop/tools/x86/lib/gcc/i586-pc-haiku/7.3.0/libsupc++.la
- /boot/system/lib/x86/libsupc++.so

**Comment by adamfowleruk** [comment]
Hi there,

Thanks for you bug report. I've not got a lot of time right now to have a look, but I've seen something similar before, and that fix may help.

Open your project and list the libraries it is using from the menu. Untick the libsupc library. Now try and rebuild.

Let me know if this works or not. Development of Paladin historically was done on one architecture and not thoroughly tested on another. I hope to fix this with automated testing in future.

**Comment by dewf** [comment]
(assuming you're referring to Project > Change system libraries) ... unfortunately there is no libsupc++ there - screenshot below.

I'm new to Haiku so this whole dual GCC thing is pretty confusing. I do notice that, in the /lib folder nearest to where that version of `ld` is being invoked from (`/packages/gcc-2.95.3_2017_07_20-2/.self/develop/lib`), there is no libsupc++.so to begin with (nor in the `/system/lib/` folder that they're all symlinked to).

I did a quick search through the project and libsupc++ appears to be hardcoded in a couple places in `Project.cpp`. Perhaps a platform detection issue?

Sorry I can't be of more help!

screenshot:
![libraries](https://user-images.githubusercontent.com/1072976/54497864-6dd5dc00-48c5-11e9-9f31-db7db948d2a1.png)

**Comment by dewf** [comment]
Just wanted to add, I played around with this a bit more, and I was able to create a project and build it by opening a terminal window and running `setarch x86`, and then launching Paladin from that same terminal window immediately after (versus from the Deskbar shortcut). So I guess it was a matter of getting it to use the gcc7 toolchain, instead of the old 2.95 one.

**Comment by adamfowleruk** [comment]
Ah that is interesting. Maybe for some reason the arch on your system is set to something else... We'll have to see if we can diagnose this in future. The architecture detection is a bit basic in the current code. Thanks for the info.

**Comment by adamfowleruk** [comment]
Fixed in develop as of today. libsupc++ and libstdc++ now both removed, as they are always on the global library path no matter what version of Haiku you are using. Automatically fixes existing PLD files without prompting.
