### ISSUE TITLE
Portuguese translation available on Polyglot

### ISSUE THREAD

**Issue by victordomingos** [HaikuArchives/Paladin#247]
The translation for Portuguese (Portugal) is complete on Polyglot, and both Spanish and Italian seem to be complete or nearly complete. Can you please add these languages in the next update?

**Comment by adamfowleruk** [comment]
Thanks for this. I'll schedule for the next update.

**Comment by adamfowleruk** [comment]
Fixed. Added Italian, Spanish, Portuguese and the less-completed Romanian. Also updated the German translation. Merged to the develop branch until I do a new release, so please clone that branch and test. Thanks for the help!
