### ISSUE TITLE
Investigate and schedule features from HackStudio

### ISSUE THREAD

**Issue by diversys** [HaikuArchives/Paladin#267]
There are a few nifty looking features in SerenityOS's HackStudio.  
https://github.com/SerenityOS/serenity/tree/master/DevTools/HackStudio

https://www.youtube.com/channel/UC3ts8coMP645hZw9JSD3pqQ/search?query=DevTools

**Comment by adamfowleruk** [comment]
Are you thinking of 1. GUI Builder, and 2. Syntax highlighting? Or something else?

I think those are both roadmapped in this issues list somewhere. syntax highlighting will require dev plugins so external editors (i.e. Pe and KapiX's editor) can access that. This is roadmapped for the next milestone.

Anything else you're thinking of???

**Comment by diversys** [comment]
IIRC there is Locator feature as well as built-in console.

**Comment by adamfowleruk** [comment]
Yeah I must admit over the last couple of days I've decided the internal console is a must (A lot of paladin code executes a command and gives the output - but you can't see the built command that is executed. E.g. g++ compilation).
Not sure what you mean by Locator, but I'll take a look some more at those videos. Currently multi-file search/replace is delegated entirely to the editor in Paladin (E.g. lpe)

**Comment by diversys** [comment]
Here's a video about locator widget https://www.youtube.com/watch?v=iSIJIYuIWTw

**Comment by adamfowleruk** [comment]
Ah ok makes sense. I'll definitely add that as its a pet peeve of mine in Paladin. As you can imagine the Paladin project itself is large and spread across multiple folders.

**Comment by adamfowleruk** [comment]
Anything else @diversys ? Otherwise I'll make sure these have issues open and I'll shut this one down.

**Comment by diversys** [comment]
Looks like that's it for now :)
