### ISSUE TITLE
generate compile_commands.json

### ISSUE THREAD

**Issue by pulkomandy** [HaikuArchives/Paladin#278]
compile_commands is a file output usually from cmake, and the de facto standard for input for many other tools. I can think of YouCompleteMe (a code completion server and client plugin for vim), sourcetrail (sourcecode and data structures explorer), and probably more.

Having a way for Paladin to generate this file would make it significantly easier to use such tools with Paladin projects.

**Comment by adamfowleruk** [comment]
Description of why it is done: https://clang.llvm.org/docs/JSONCompilationDatabase.html
CMake's support: https://cmake.org/cmake/help/v3.5/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html
List of support for this file: https://github.com/cquery-project/cquery/wiki/Compilation-database
Language server supporting this file: https://github.com/cquery-project/cquery

**Comment by adamfowleruk** [comment]
@pulkomandy Hello! I've now implemented this. I've done a PR for haikuports for a new release that incorporates this feature. Note that the feature only writes out the files that were compiled in the last build. I.e. to include all compile strings for all files you need to force a full project rebuild in Paladin. The compile_commands.json file is generated in the folder alongside the PLD file.
