### ISSUE TITLE
Investigate new project crash in German translation

### ISSUE THREAD

**Issue by adamfowleruk** [HaikuArchives/Paladin#286]
Likely a B_TRANSLATE in the name of the file folder by accident, or similar misuse of B_TRANSLATE. Reported by BrunoB.

**Comment by adamfowleruk** [comment]
Can only reproduce on 2.0-1 in haiku depot. Latest build ignores locale set entirely, only ever showing English. Why???

**Comment by adamfowleruk** [comment]
non english catkeys are malformed. Crashes catkeyseditor too. Download new versions? DOS vs UNIX format?

**Comment by humdingerb** [comment]
If you've opened/edited those catkeys with CatKeysEditor, you may have run into https://github.com/puckipedia/BeLocalized/issues/16 : "Sometimes CatKeysEditor leaves garbage at the end of the file."

Normally it's best to just use the files exported from Polyglot. You may want to upload a new en.catkeys there when you added/changed the strings in the GUI, btw.

**Comment by adamfowleruk** [comment]
This is with files directly downloaded from polyglot. Here's the sequence:-

Error:

```text
for lc in de en es it pt ro ; do linkcatkeys -o ./Paladin -s application/x-vnd.dw-Paladin -tr -l $lc locales/$lc.catkeys; done
couldn't load source-catalog locales/de.catkeys - error: Bad data
couldn't load source-catalog locales/es.catkeys - error: Bad data
couldn't load source-catalog locales/it.catkeys - error: Bad data
couldn't load source-catalog locales/pt.catkeys - error: Bad data
couldn't load source-catalog locales/ro.catkeys - error: Bad data
/boot/system/develop/etc/makefile-engine:383: recipe for target 'bindcatalogs' failed
```

From the above English works, but the other languages do not. I've even replaced my local de.catkeys with one downloaded from polyglot.

Reading linkcatkeys source the error message comes from here:-
https://github.com/haiku/haiku/blob/master/src/tools/locale/linkcatkeys.cpp#L109

This references PlainTextCatalog. Only place B_BAD_DATA could be returned is in a commented out section:-
https://github.com/haiku/haiku/blob/master/src/tools/locale/PlainTextCatalog.cpp#L242

Which is impossible, unless the version of linkcatkeys in all the recent builds doesn't have this commented out. Only problem is, this code hasn't changed in 10 years.

I'll ask PulkoMandy to take a look once I get a decent net connection (on a train). I can't find anywhere else B_BAD_DATA would be returned from.

**Comment by humdingerb** [comment]
I checked out the latest Paladin source and the en.catkeys have a fingerprint of 1273216190. The de.catkeys from Polyglot have 2226395208. Maybe you re-created the English catkeys (make catkeys) and didn't upload them to Polyglot?

**Comment by adamfowleruk** [comment]
Ah I was under the impression that the fingerprint was unique to that file, not to the version of the source language used for the translations. I take it that isn't the case?

**Comment by humdingerb** [comment]
The fingerprint is generated from all the strings when "make catkeys" scans the files. If you translate "manually", you copy the en.catkeys to xx.catkeys and start translating (without touching the fingerprint).
If you change or add a string, the fingerprint changes when the new en.catkeys is generated and the older versions of xx.catkeys won't work anymore. CatKeysEditor has an "Import" function to get the already translated strings into the new en.catkeys copy. Polyglot adjusts all translations when you upload a new en.catkeys file.

**Comment by adamfowleruk** [comment]
Righto. I'll add the upload of EN and download of other languages to my personal workflow. I've added a new enhancement idea for automating this in Paladin somehow

**Comment by adamfowleruk** [comment]
I've reuploaded the en catkeys and downloaded all the catkeys. I still get the same error. Check out the below output - all looks ok to me

```sh
~/git/Paladin/Paladin> head -n 1 locales/*
==> locales/de.catkeys <==
1       German  application/x-vnd.dw-Paladin    1273216190

==> locales/en_GB.catkeys <==
1       English (British)       application/x-vnd.dw-Paladin    1273216190

==> locales/en.catkeys <==
1       English application/x-vnd.dw-Paladin    1273216190

==> locales/es.catkeys <==
1       Spanish application/x-vnd.dw-Paladin    1273216190

==> locales/fr.catkeys <==
1       French  application/x-vnd.dw-Paladin    1273216190

==> locales/hr.catkeys <==
1       Croatian        application/x-vnd.dw-Paladin    1273216190

==> locales/it.catkeys <==
1       Italian application/x-vnd.dw-Paladin    1273216190

==> locales/pt.catkeys <==
1       Portuguese      application/x-vnd.dw-Paladin    1273216190

==> locales/ro.catkeys <==
1       Romanian        application/x-vnd.dw-Paladin    1273216190

==> locales/sv.catkeys <==
1       Swedish application/x-vnd.dw-Paladin    1273216190
```

I've ran make catkeys to get the en version. Any ideas please @humdingerb ???

**Comment by humdingerb** [comment]
No idea ATM... I tried to build Paladin, but it fails:

```
/Source/Paladin> ./buildsuite.sh 1
Building Paladin
g++ -c QuickFindWindow.cpp  -I./  -IBuildSystem/  -ISourceControl/  -IThirdParty/  -Iobjects.x86-cc2-release/ -I-   -O1   -D_ZETA_TS_FIND_DIR_  -o "objects.x86-cc2-release/QuickFindWindow.o"
/Source/Paladin/Paladin/QuickFindWindow.cpp:10: directory `/boot/system/develop/headers/os/locale' specified in #include
/Source/Paladin/Paladin/QuickFindWindow.cpp:558: macro `isupper' used with too many (2) args
/Source/Paladin/Paladin/QuickFindWindow.cpp:567: macro `toupper' used with too many (2) args
/boot/system/develop/etc/makefile-engine:297: recipe for target 'objects.x86-cc2-release/QuickFindWindow.o' failed
make: *** [objects.x86-cc2-release/QuickFindWindow.o] Error 1
for lc in de en es it pt ro fr en_GB hr sv ; do linkcatkeys -o ./Paladin -s application/x-vnd.dw-Paladin -tr -l $lc locales/$lc.catkeys; done
couldn't load source-catalog locales/de.catkeys - error: Bad data
couldn't write target-resource to ./Paladin - error: No such file or directory
couldn't load source-catalog locales/es.catkeys - error: Bad data
couldn't load source-catalog locales/it.catkeys - error: Bad data
couldn't load source-catalog locales/pt.catkeys - error: Bad data
couldn't load source-catalog locales/ro.catkeys - error: Bad data
couldn't load source-catalog locales/fr.catkeys - error: Bad data
couldn't load source-catalog locales/en_GB.catkeys - error: Bad data
couldn't load source-catalog locales/hr.catkeys - error: Bad data
couldn't load source-catalog locales/sv.catkeys - error: Bad data
/boot/system/develop/etc/makefile-engine:383: recipe for target 'bindcatalogs' failed
make: *** [bindcatalogs] Error 255
Building temporary project SymbolFinder.nodebug.pld
./buildsuite.sh: Zeile 47: /Source/Paladin/Paladin/Paladin: No such file or directory
```

**Comment by adamfowleruk** [comment]
Are you looking at the latest develop branch, or master? I don't get that on develop. Also what hrev are you on?

**Comment by humdingerb** [comment]
Yep, on the "develop" branch with Haiku hrev53636, 32bit.

**Comment by adamfowleruk** [comment]
I'm the same, except on 64 bit. Surely that can't make a difference to the core libraries for std::string?

**Comment by adamfowleruk** [comment]
The project crash is due to the translated version of the 'Templates' folder not existing. This is a bad way to do translations anyway, as it relies on those translations in the main app package. I've removed the support for translated folder for now. Nothing stopping someone creating a hpkg for translated templates and storing them under /boot/system/develop/Paladin/Templates/ - this location is checked for by Paladin, allowing extensibility.
