### ISSUE TITLE
Window position reminder doesn't check visibility

### ISSUE THREAD

**Issue by adamfowleruk** [HaikuArchives/Paladin#304]
Bug in #300 - If the last position was stored on a large res screen, and you're now on a low res screen, the window is drawn off the display. No way to fix without a larger monitor!
Add a check to ensure it's drawn on screen.

**Comment by CodeforEvolution** [comment]
BWindow provides a handy “MoveOnScreen” function for this. It is not documented yet, so you’ll need to look in its header: https://github.com/haiku/haiku/blob/master/headers/os/interface/Window.h

**Comment by adamfowleruk** [comment]
Nice! Thanks for the hint.

**Comment by adamfowleruk** [comment]
Also don't forget to ensure Workspace number is used in saved settings, too, for those with multiple workspaces.

**Comment by humdingerb** [comment]
Maybe a checkbox in the settings is in order for that, "Open projects on last saved workspace" or something.
I may want to open a project on my current workspace and might be irritated if nothing pops up and I have to go ahunting...

**Comment by adamfowleruk** [comment]
Hmmmm good point... I'll have a think
