### ISSUE TITLE
Question: Do you want contributors to add personal copyright statements, or not?

### ISSUE THREAD

**Issue by adamfowleruk** [HaikuArchives/Paladin#32]
Happy to copyright to myself, or Haiku Project, or whatever. Do let me know.

**Comment by scottmc** [comment]
in general, for apps on HaikuArchives, search through the source files and try to copy the style of the program.  This one for example if you look in AboutWindow.cpp you'll see a couple of authors listed.  Add yourself to any source files you end up modifying. They are usually in order from original author to latest authors.
