### ISSUE TITLE
Alt+m (Make project) shortcut doesn't work

### ISSUE THREAD

**Issue by diversys** [HaikuArchives/Paladin#324]

**Comment by adamfowleruk** [comment]
Works on my machine. :) Please provide more detail. Was a Paladin window definitely selected?

**Comment by diversys** [comment]
Actually, Alt+m works but CMD+m doesn't even though CMD is mapped to Alt in VMware keymappings. I can see that "m" is not pressed on CMD+m in Keymap preflet. So, not a Paladin bug. 

![image](https://user-images.githubusercontent.com/1316513/71545422-e06b0080-299b-11ea-8f35-b08922aea9e0.png)

**Comment by diversys** [comment]
CMD+m and CMD+h doesn't work, everything else works, go figure.

**Comment by adamfowleruk** [comment]
Weird. I use the default key mappings in vmware fusion, so Alt+M works fine for me.
