### ISSUE TITLE
Two pixels inner border on the left of the window

### ISSUE THREAD

**Issue by diversys** [HaikuArchives/Paladin#326]
![image](https://user-images.githubusercontent.com/1316513/71541153-82232b00-2965-11ea-83cd-acf91ee793ff.png)

**Comment by adamfowleruk** [comment]
Accepted. Will check.

**Comment by adamfowleruk** [comment]
Not an issue on the develop branch version. Which version were you using @diversys ?

**Comment by diversys** [comment]
I still can see it in current head d7781c27c575f386e266c5b3a282daaad93f4f8a.

**Comment by adamfowleruk** [comment]
Bizarre. What Haiku version are you on?

**Comment by diversys** [comment]
I'm always on latest 64bit nightly.

**Comment by diversys** [comment]
Looks like a small issue in BeDecorator, sorry for the noise.
