### ISSUE TITLE
Remove R1a4 support

### ISSUE THREAD

**Issue by waddlesplash** [HaikuArchives/Paladin#5]
- New directory constants (discussed in b9e80905108d4717e5dfd01cddc106dee7e1691f and 7d6207361b93ef4cf6e599bf454e48d9e574c53c)
- Makefile generation

**Comment by adamfowleruk** [comment]
@waddlesplash Can you please confirm these are no longer valid, given the updated build script? Thanks.

**Comment by waddlesplash** [comment]
What is the new build script?

**Comment by adamfowleruk** [comment]
The commits mention build.sh and a few other files with similar names. There's now just a single build script that builds the lot. It also uses makefile-engine, which one of the commits mentions we should migrate to.

I think the work has been done already, but I just wanted to make sure.

Thanks!

**Comment by waddlesplash** [comment]
Hmm, suppose so.

**Comment by adamfowleruk** [comment]
OK great, thanks.
