### ISSUE TITLE
ProjectWindow doesn't remember previous dimensions

### ISSUE THREAD

**Issue by adamfowleruk** [HaikuArchives/Paladin#50]
Save the main Project Window dimensions/position so it appears correctly the next time it is opened.

**Comment by adamfowleruk** [comment]
Fixed by recent PR

**Comment by scottmc** [comment]
Try to match the commits to ticket closures, it might come in handy later in case of regressions.

**Comment by humdingerb** [comment]
If you add a "Fixes #50" in the last line of your commit message, the issue is closed automatically.

**Comment by adamfowleruk** [comment]
Yeah I have been doing, but I noticed afterwards that a PR for a different issue then also solved this issue.
