### ISSUE TITLE
Status bar issues

### ISSUE THREAD

**Issue by adamfowleruk** [HaikuArchives/Paladin#51]
** Misalignment **
See the below image. Slight misalignment with the status bar.

![paladin-status-scroll-bars](https://user-images.githubusercontent.com/2700521/46039384-795dfc80-c105-11e8-8cbc-bc089b007bff.png)

** Status bar area not used **
Should probably write out the status here at some point. E.g. last saved/opened/new file added, built OK, etc.

**Comment by diversys** [comment]
misalignment with the status bar is still there.

**Comment by adamfowleruk** [comment]
Yes good point. I fixed one issue and not the other. I'm going to use your newly reported bug for the alignment issue, as I think it's related to the border issue, so I'll keep this one closed.
