### ISSUE TITLE
List header files

### ISSUE THREAD

**Issue by tsyesika** [HaikuArchives/Paladin#8]
Currently the list of files in a project doesn't list the header files just the .cpp (and other files). It would be useful if it could list the header files too.

**Comment by jscipione** [comment]
I agree, with this, would be nice for it to add .h files by default since I often want to edit them from within Paladin.

**Comment by adamfowleruk** [comment]
I'm going to have a go at adding this now...

**Comment by adamfowleruk** [comment]
I've got the code to a state where it is showing a separate header files section and listing the header files mentioned in the Dependency section of the project file (same group level in the project file).

Changes are here: https://github.com/adamfowleruk/Paladin/tree/feature-8

The header file names aren't interactive yet. That shouldn't be hard to fix. I'll do a pull request once I've solved that and tested.

**Comment by adamfowleruk** [comment]
Fixed in above PR with header file opening and editing.
